[package]
name = "arch_x86_64"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
hal = { path = "../hal" }
x86_64 = "0.15"
pic8259 = "0.11"
spin = "0.9"

[lib]
path = "src/lib.rs"
