[target.x86_64-unknown-none]
rustflags = [
  "-C", "link-arg=-T../../crates/kernel/linker.ld",
  "-C", "relocation-model=static",
  "-C", "code-model=kernel",
  "-C", "no-redzone=yes",
  "-C", "panic=abort",
]
