[target.x86_64-unknown-none]
rustflags = [
  "-C", "link-arg=-Tcrates/kernel/linker.ld",
  "-C", "relocation-model=static",
  "-C", "code-model=kernel",
  "-C", "no-redzone=yes",
  "-C", "panic=abort",
]

[target.aarch64-unknown-none]
rustflags = [
  "-C", "link-arg=-Tcrates/kernel/linker_aarch64.ld",
  "-C", "relocation-model=static",
  "-C", "code-model=small",
  "-C", "panic=abort",
]
