[package]
name = "user_text_editor"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]

[lib]
path = "src/lib.rs"

[[bin]]
name = "text-editor"
path = "src/main.rs"
test = false
bench = false
