[package]
name = "platform_qemu_x86_64"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
arch_x86_64 = { path = "../arch_x86_64" }
kernel_core = { path = "../kernel_core" }

[lib]
path = "src/lib.rs"
