[package]
name = "note_piece"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]

[lib]
name = "note_piece"
path = "src/lib.rs"

[[bin]]
name = "note-piece"
path = "src/main.rs"
test = false
bench = false

[workspace]
